# Generated by Django 5.0.6 on 2025-03-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(default="SOME STRING, Author", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="SOME STRING, Title", max_length=200),
        ),
    ]
